### ISSUE TITLE
Fix Schema Error

### ISSUE THREAD

**Issue by varokas** [ETDA/etax-schema#4]
The current schema is broken. Right now we validate that by simply running it through java `xjc` tool. 

1. If you have a better tool. Please suggest one (or better: send a PR with an appropriate edit to .travis.yml)
2. Fixing the schema might require multiple Pull Requests. Any changes that make the schema less broken is appreciated. Please reference back to this issue when you made the PR. https://help.github.com/articles/autolinked-references-and-urls/

You can see the current status of master here:
[![Build Status](https://travis-ci.org/ETDA/etax-schema.svg?branch=master)](https://travis-ci.org/ETDA/etax-schema)

**Comment by champillon** [comment]
if we put all xsd in the same folder (and fix the path in schemaLocation and fix the ThaiMessageFunctionCodeContentType duplication by comment out the non-Thai) then we can run "xjc" pass
<img width="254" alt="screen shot 2560-09-09 at 3 49 00 pm" src="https://user-images.githubusercontent.com/1620789/30238719-b87588d6-9576-11e7-90fd-601305def16e.png">

but if leave with the extracted folder will found out this error
<img width="1003" alt="screen shot 2560-09-09 at 3 52 30 pm" src="https://user-images.githubusercontent.com/1620789/30238722-ea50c668-9576-11e7-8cda-a03691f165f9.png">

**Comment by champillon** [comment]
seem that @varokas fix the error above on https://github.com/ETDA/etax-schema/pull/5

**Comment by varokas** [comment]
1 error down. Now we are dealing with new error =) 

```
[ERROR] 'MessageFunctionCode' is already defined
  line 28 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/UNECE_MessageFunctionCode_D14A.xsd
[ERROR] (related to above error) the first definition appears here
  line 28 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiMessageFunctionCode_1p0.xsd
[ERROR] 'MessageFunctionCodeContentType' is already defined
  line 558 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/UNECE_MessageFunctionCode_D14A.xsd
[ERROR] (related to above error) the first definition appears here
  line 34 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiMessageFunctionCode_1p0.xsd
[ERROR] 'ThaiDocumentNameCodeInvoice' is already defined
  line 51 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd
[ERROR] (related to above error) the first definition appears here
  line 51 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd
[ERROR] 'ThaiDocumentNameCodeInvoiceContentType' is already defined
  line 122 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/uncefact/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd
[ERROR] (related to above error) the first definition appears here
  line 57 of file:/home/travis/build/ETDA/etax-schema/schema/XMLSchemaV2/ETDA/codelist/standard/ThaiDocumentNameCode_Invoice_1p0.xsd```

**Comment by champillon** [comment]
This error may wait for @NopponP to confirm which xsd we can remove out (ThaiMessageFunctionCode or UNECE_MessageFunctionCode_D14A.xsd)

**Comment by varokas** [comment]
Can you provide the diff result on what is the difference between the two ?

**Comment by champillon** [comment]
Ok doing it tmr.

**Comment by varokas** [comment]
@champillon - green build !! =). See above

**Comment by champillon** [comment]
@varokas I think it shoud be the unece one coz in previous facebook chat @NopponP told us to remove unece somehow wait for him to reconfirm

**Comment by varokas** [comment]
Look at the pull request. I explained which one to remove for each case and the reasons

**Comment by champillon** [comment]
ok

**Comment by varokas** [comment]
Build pass now. I'll close this issue.
